name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up cache
        uses: actions/cache@v5
        with:
          path: /var/apt/cache/archives
          key: ${{runner.os}}-packages
      - name: Install apt packages
        run: |-
          sudo apt-get -q update
          sudo apt-get $APT_OPTS install $PACKAGES
        env:
          APT_OPTS: >-
            -yq --no-install-suggests --no-install-recommends
          PACKAGES: >-
            coffeescript
            crystal
            elixir
            fpc
            gawk
            groovy
            hyperfine
            libjson-parse-perl
            livescript
            lua5.4
            mono-mcs
            nim
            octave
            r-base
            rakudo
            valac
            zsh
      - name: Install Dart
        run: |-
          curl -JLO $DEB && sudo dpkg -i dart_3.12.1-1_amd64.deb
          echo '/usr/lib/dart/bin' >> "$GITHUB_PATH"
        env:
          DEB: https://storage.googleapis.com/dart-archive/channels/stable/release/latest/linux_packages/dart_3.12.1-1_amd64.deb
        working-directory: /tmp
      - name: Install Deno
        run: |-
          curl -JLO $URL && unzip deno-x86_64-unknown-linux-gnu.zip
          sudo mv deno /usr/bin/deno
        env:
          URL: https://github.com/denoland/deno/releases/download/v2.8.1/deno-x86_64-unknown-linux-gnu.zip
        working-directory: /tmp
      - name: Install DMD
        run: curl -JLO $DEB && sudo dpkg -i dmd_2.112.0-0_amd64.deb
        env:
          DEB: https://downloads.dlang.org/releases/2026/dmd_2.112.0-0_amd64.deb
        working-directory: /tmp
      - name: Install Fennel
        run: |-
          curl -JLO $URL && chmod +x fennel-1.6.1
          sudo mv fennel-1.6.1 /usr/bin/fennel
        env:
          URL: https://fennel-lang.org/downloads/fennel-1.6.1
        working-directory: /tmp
      - name: Install Scala 2
        run: curl -JLO $DEB && sudo dpkg -i scala-2.13.18.deb
        env:
          DEB: https://github.com/scala/scala/releases/download/v2.13.18/scala-2.13.18.deb
        working-directory: /tmp
      - name: Install Scala 3 CLI
        run: curl -JLO $DEB && sudo dpkg -i scala-cli-x86_64-pc-linux.deb
        env:
          DEB: https://github.com/VirtusLab/scala-cli/releases/download/v1.14.0/scala-cli-x86_64-pc-linux.deb
        working-directory: /tmp
      - name: Set up PostgreSQL
        run: |-
          sudo systemctl start postgresql.service && pg_isready
          sudo -u postgres createuser --superuser $USER
          sudo -u postgres createdb 7SegmentDisplays
      - name: Set up MySQL
        run: |-
          sudo -E sh -c 'printf "$MYSQL_CNF" >>/etc/mysql/my.cnf'
          sudo systemctl start mysql.service && mysqladmin ping
          mysql -e 'CREATE DATABASE 7SegmentDisplays;'
        env:
          MYSQL_CNF: |
            [client]
            user=root
            password=root
            loose-local-infile=1
            [mysqld]
            local_infile=1
            secure-file-priv=
      - name: Compile programs
        run: make all
      - name: Run tests
        run: make test
      - name: Run benchmarks
        run: make bench
        if: github.event_name == 'push'
      - name: Setup Pages
        uses: actions/configure-pages@v5
        if: github.event_name == 'push'
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        if: github.event_name == 'push'
        with:
          source: .
          destination: _site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        if: github.event_name == 'push'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        if: github.event_name == 'push'
